apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: homefinder
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: ghcr.io/byrnedo/homefinder
            imagePullPolicy: Always
