apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: homefinder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: cache
            hostPath:
              path: /opt/homefinder
          containers:
          - name: cron
            image: ghcr.io/byrnedo/homefinder@sha256:e4ae02e2016b23281ccbca77d3d7d560f6d6f836eb284550f5877daa21703079
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /cache
              name: cache
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: slack_webhook_url
