apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: homefinder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: cache
            hostPath:
              path: /opt/homefinder
          containers:
          - name: cron
            image: ghcr.io/byrnedo/homefinder@sha256:e0b25f380bcc20a5cae1f5068e9ca29d05768f2bc3bb6ba2190769e9d5c575c9
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /cache
              name: cache
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: slack_webhook_url
