apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: homefinder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: cache
            hostPath:
              path: /opt/homefinder
          containers:
          - name: cron
            image: ghcr.io/byrnedo/homefinder@sha256:d91a878b4f8f1b7d33bf6cca97b49ee492086f68c4d917bbba3a19e5f3f0ce5a
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /cache
              name: cache
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: slack_webhook_url
