apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: homefinder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: cache
            hostPath:
              path: /opt/homefinder
          containers:
          - name: cron
            image: ghcr.io/byrnedo/homefinder@sha256:375b7730dbb464ca3e703ac304813d96e73c4a00c810e9ebef3cdf8f2a0f7891
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /cache
              name: cache
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: slack_webhook_url
            - name: CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: config
                  key: credentials
            - name: SPREADSHEET_ID
              valueFrom:
                secretKeyRef:
                  name: config
                  key: spreadsheet_id
