apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: homefinder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: cache
            hostPath:
              path: /opt/homefinder
          containers:
          - name: cron
            image: ghcr.io/byrnedo/homefinder:latest@sha256:35ce657c268d1b28a8a06141fade60a783d3162976e9d9a380608657a46dc881
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /cache
              name: cache
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: slack_webhook_url
